// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "http://petstore.swagger.io/api",
  },
});

export default function() {
  group("pets", function() {
    postman[Request]({
      name: "find Pets",
      id: "294c5fd1-a1c7-4db5-8663-335d112157ee",
      method: "GET",
      address: "{{baseUrl}}/pets?tags=<string>&tags=<string>&limit=<integer>",
      headers: {
        Accept: "application/json",
      },
    });

    postman[Request]({
      name: "add Pet",
      id: "52676fd0-c7b7-45c0-ba31-b88a04c838a6",
      method: "POST",
      address: "{{baseUrl}}/pets",
      data: '{\n  "name": "<string>",\n  "tag": "<string>"\n}',
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    });

    group("{id}", function() {
      postman[Request]({
        name: "get Pet By Id",
        id: "093cda01-eb08-4351-8d51-4bca5db402ad",
        method: "GET",
        address: "{{baseUrl}}/pets/<long>",
        headers: {
          Accept: "application/json",
        },
      });

      postman[Request]({
        name: "delete Pet",
        id: "c3d3bd1d-b525-40b0-a06d-7dd71cb3f0d5",
        method: "DELETE",
        address: "{{baseUrl}}/pets/<long>",
        headers: {
          Accept: "application/json",
        },
      });
    });
  });
}
